spring:
  data:
    mongodb:
      host: localhost
      database: piggymetrics
      port: 27017

server:
  servlet:
    context-path: /uaa
  port: 5000
  
eureka:
  instance:
    prefer-ip-address: true
